const TODOS_TYPES = {
    ERROR: 'ERROR',
    SUCCESS: 'SUCCESS',
    LOADING: 'LOADING',
    SYNCHRONIZATION: "SYNCHRONIZATION",
    FILTER: "FILTER",
    COUNT: "COUNT",
    SEARCH: "SEARCH",
    SAVE: "SAVE",
    OPEN_MODAL: "OPEN_MODAL"
};

export default TODOS_TYPES;